set -s escape-time 50
set -g default-terminal "tmux-256color"
set -g default-shell /usr/bin/zsh

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

set -g pane-active-border-style 'fg=#4fbb5b'
set -g pane-border-style 'fg=#102e18'
set -g status-style 'bg=#333333 fg=#4fbb5b'
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

