set -s escape-time 50
set -g default-terminal "tmux-256color"
set -g default-shell /usr/bin/zsh

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

set -g pane-active-border-style 'fg=#4fbb5b'
set -g pane-border-style 'fg=#102e18'
set -g status-style 'bg=#ECEFF4 fg=#5E81AC'
set -g base-index 1
set -g mouse on

# Inactive window indicator.
set -g window-status-format "#[bg=#ECEFF4 fg=#4C566A] #{window_index} #[default]"
# Active window indicator.
set -g window-status-current-format "#[bg=#B3C9E3 fg=#2E3440] #{window_index} #[default]"

# Empty the left part of the bar.
set -g status-left ""

# Add time and date to the right.
set -g status-right "#[fg=#4C566A] #S  %H:%M:%S #[fg=#4C566A] %d-%m-%Y "

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching.
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

